name: siakad
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ICONS
  cupertino_icons: ^1.0.8

  # NETWORKING
  dio: ^5.9.0
  http: ^1.2.1

  # STORAGE
  shared_preferences: ^2.5.3

  # UI & POPUP
  quickalert: ^1.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.0

  # EXTRA UI
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  provider: ^6.1.2

  # CONNECTIVITY
  connectivity_plus: ^6.1.0
  
  # LOCATION (untuk absensi)
  geolocator: ^14.0.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Aktifkan jika ada assets
  # assets:
  #   - assets/
  #   - images/

  # Aktifkan jika ada custom font
  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: fonts/MyFont.ttf